trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-file-upload-web-app - Build'
  
variables:
  azureSubscription: 'Demo Account'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'CI'
    azureSubscription: ${{ variables.azureSubscription }}
    webAppName: 'demo-file-upload-web-app'
    resourceGroupName: 'demo-file-upload-web-app'
    region: 'East US'
    storageAccountConnectionString: ${{ variables.StorageAccountConnectionString }}
    packageName: 'Demo.FileUploadWebApp.Server'